version: '3'
services:
  remix:
    image: bill-fetcher-remix
    container_name: bill-fetcher-remix
    env_file:
    - remix-token.env
    # command: 
    # - "invoice"

  sbi:
    image: bill-fetcher-sbi
    container_name: bill-fetcher-sbi
    volumes:
        - ./:/data/
    env_file:
    - sbi-token.env

  water:
    image: bill-fetcher-tokyowater
    container_name: bill-fetcher-tokyowater
    volumes:
        - ./:/data/
    env_file:
    - tokyowater-token.env
