version: '3'
services:
  # selenium:
  #   image: selenium/standalone-chrome:4.1.4-20220427
  #   container_name: selenium
  #   ports:
  #     - 4444:4444
  #     - 7900:7900
  #   volumes:
  #     - /dev/shm:/dev/shm

  # money-forward:
  #   image: bill-fetcher-money-forward
  #   container_name: bill-fetcher-money-forward
  #   env_file:
  #   - money-forward.env
  #   volumes:
  #   - ./:/data/

  fetcher-sbi:
    image: bill-fetcher-sbi
    container_name: bill-fetcher-sbi
    env_file:
    - sbi-token.env
    volumes:
    - ./:/data/
