version: '3'
services:
  # money-forward:
  #   image: bill-fetcher-money-forward
  #   container_name: bill-fetcher-money-forward
  #   env_file:
  #   - money-forward.env
  #   volumes:
  #   - ./:/data/

  au:
    image: bill-fetcher-au
    container_name: bill-fetcher-au
    env_file:
    - au-token.env
    volumes:
    - ./.cookies:/.cookies
    command:
    - "--login-2fa"

  # remix:
  #   image: bill-fetcher-remix
  #   container_name: bill-fetcher-remix
  #   env_file:
  #   - remix-token.env
  #   command: 
  #   - "invoice"

  # sbi:
  #   image: bill-fetcher-sbi
  #   container_name: bill-fetcher-sbi
  #   volumes:
  #       - ./:/data/
  #   env_file:
  #   - sbi-token.env

  # water:
  #   image: bill-fetcher-tokyowater
  #   container_name: bill-fetcher-tokyowater
  #   volumes:
  #       - ./:/data/
  #   env_file:
  #   - tokyowater-token.env

  # nicigas:
  #   image: bill-fetcher-nicigas
  #   container_name: bill-fetcher-nicigas
  #   env_file:
  #   - nicigas-token.env
  #   volumes:
  #   - ./:/data/

  # auelect:
  #   image: bill-fetcher-auelect
  #   container_name: bill-fetcher-auelect
  #   volumes:
  #   - ./:/data/
